### ISSUE TITLE
TemplateDoesNotExist at /actividad/

### ISSUE THREAD

**Issue by CarlosCatalan** [hbkfabio/asignacion_horario#1]
parametros/actividad.html

Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/actividad/
Django Version: 	1.11.3
Exception Type: 	TemplateDoesNotExist
Exception Value: 	

parametros/actividad.html

Exception Location: 	/home/carlos/Documentos/Repositorio/Python3/lib/python3.4/site-packages/django/template/engine.py in find_template, line 148
Python Executable: 	/home/carlos/Documentos/Repositorio/Python3/bin/python
Python Version: 	3.4.0
Python Path: 	

['/home/carlos/Documentos/Repositorio/asignacion_horario',
 '/home/carlos/Documentos/Repositorio/Python3/lib/python3.4',
 '/home/carlos/Documentos/Repositorio/Python3/lib/python3.4/plat-x86_64-linux-gnu',
 '/home/carlos/Documentos/Repositorio/Python3/lib/python3.4/lib-dynload',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/home/carlos/Documentos/Repositorio/Python3/lib/python3.4/site-packages']

Server time: 	Mar, 4 Jul 2017 12:18:17 -0400

**Comment by hbkfabio** [comment]
Fixed.

Please update the git repository (git pull) and try the "actividad" link.
