### ISSUE TITLE
ProgrammingError at /modulo/

### ISSUE THREAD

**Issue by CarlosCatalan** [hbkfabio/asignacion_horario#3]
column parametros_modulo.carrera_id does not exist
LINE 1: ...etros_modulo"."id", "parametros_modulo"."nombre", "parametro...
                                                             ^

Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/modulo/
Django Version: 	1.11.3
Exception Type: 	ProgrammingError
Exception Value: 	

column parametros_modulo.carrera_id does not exist
LINE 1: ...etros_modulo"."id", "parametros_modulo"."nombre", "parametro...
                                                             ^

Exception Location: 	/home/carlos/Documentos/Repositorio/Python3/lib/python3.4/site-packages/django/db/backends/utils.py in execute, line 65
Python Executable: 	/home/carlos/Documentos/Repositorio/Python3/bin/python
Python Version: 	3.4.0
Python Path: 	

['/home/carlos/Documentos/Repositorio/asignacion_horario',
 '/home/carlos/Documentos/Repositorio/Python3/lib/python3.4',
 '/home/carlos/Documentos/Repositorio/Python3/lib/python3.4/plat-x86_64-linux-gnu',
 '/home/carlos/Documentos/Repositorio/Python3/lib/python3.4/lib-dynload',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/home/carlos/Documentos/Repositorio/Python3/lib/python3.4/site-packages']

Server time: 	Mar, 4 Jul 2017 12:21:23 -0400

**Comment by hbkfabio** [comment]
Fixed.

Please run:
* git pull
* python manage.py makemigrations
* python manage.py migrate

and re-run the runserver
